### ISSUE TITLE
When stable version is coming

### ISSUE THREAD

**Issue by mirzaawais** [LAS-IT/formstack-api#1]
Hi, I want to use your wrapper. But you have written it is under development and functions will be changed or deprecated. So when you are releasing stable version of this wrapper? And should I use without waiting for stable version if you don't see any major changes?

Regards,
Awais qarni

**Comment by danreedy** [comment]
At this point the API is stable in our implementation. You should be fine to start using it for your needs. If you come across any issues please submit an issue or a pull request and we'll incorporate it in. Thanks.
